{
 "title": "Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(user_total{method=\"active-users\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "rate(auth_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "purchase_total{method=\"pizza-latency\", source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "request_total{method=\"latency\", source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purchase_total{method=\"revenue\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(purchase_total{method!=\"revenue\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}