{
 "title": "Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(user_total{method=\"active-users\"}[1m])",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "targets": [
    { "expr": "rate(auth_total[1m])", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "purchase_total{method=\"pizza-latency\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "request_total{method=\"latency\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(purchase_total{method=\"revenue\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 7 },
   "targets": [
    { "expr": "rate(request_total[1m])", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(purchase_total{method!=\"revenue\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_total", "legendFormat": "{{method}}" }
   ]
  }
 ]
}